---
- hosts: localhost
  tasks:

    - name: install packages for building torque
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'libxml2-devel'
        - 'boost-devel'
        - 'hwloc'
        - 'hwloc-devel'

    - pip:
        name: pexpect

    - name: download torque source
      get_url:
        url: http://wpfilebase.s3.amazonaws.com/torque/torque-6.1.0.tar.gz
        dest: /root/torque-6.1.0.tar.gz
        checksum: sha256:c93585f024720df3e3e360eeb25df4990a9ed85362ac3e7adec6c7a13f8e62d2

    - name: extract torque
      unarchive:
        src: /root/torque-6.1.0.tar.gz
        dest: /root
        remote_src: True

    - name: run configure
      command: ./configure --enable-cgroups --with-momlogdir
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/config.status

    - name: run make
      command: make
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_success

    - name: test if make worked
      command: touch make_success
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_success

    - name: run make install
      command: make install
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_install_success

    - name: test if make install worked
      command: touch make_install_success
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_install_success

    - name: create hwloc config file
      command: touch /etc/ld.so.conf.d/hwloc.conf
      args:
        creates: /etc/ld.so.conf.d/hwloc.conf

    - name: configure hwloc
      lineinfile:
        dest: /etc/ld.so.conf.d/hwloc.conf
        line: '/usr/local/lib'

    - name: run ldconfig
      command: ldconfig

# TODO the hostnamne given by the hostname command, must be the first entry in the /etc/hosts for 127.0.0.1


    - name: initial server db
      expect:
        command: ./torque.setup root
        responses:
          (?i)wish: "y"
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/initial_server_db_success
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/usr/local/sbin"

    - name: create file to show server db initialize worked
      command: touch initial_server_db_success
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/initial_server_db_success

# echo /usr/local/lib >/etc/ld.so.conf.d/hwloc.conf

#test torque server
#download maui
#uncompress maui
#configure maui
#make maui
#make install maui
#test maui
