---
- hosts: localhost
  tasks:
#    - name: download torque source
#      get_url:
#        url: http://wpfilebase.s3.amazonaws.com/torque/torque-6.1.0.tar.gz
#        dest: /root/torque-6.1.0.tar.gz

    - name: install packages for building torque
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'libxml2-devel'
        - 'boost-devel'
        - 'hwloc'
        - 'hwloc-devel'

    - name: download and extract torque
      unarchive:
        src: http://wpfilebase.s3.amazonaws.com/torque/torque-6.1.0.tar.gz
        dest: /root
        remote_src: True

    - name: run configure
      command: ./configure --enable-cgroups --with-momlogdir
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/config.status

    - name: run make
      command: make
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_success

    - name: test if make worked
      command: touch make_success
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_success

    - name: run make install
      command: make install
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_install_success

    - name: test if make install worked
      command: touch make_install_success
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_install_success

    # download torque
    # extract
    # install packages related to rpmbuild
    # build torque rpm
    # scp to file server
