---
# http://docs.adaptivecomputing.com/torque/6-1-0/adminGuide/help.htm
- hosts: master
  tasks:
    - name: configure hosts file
      lineinfile:
        dest: /etc/hosts
        line: '192.168.50.5 client1'
        create: yes
      become: yes
      become_user: root

    - name: install packages for building torque
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'libxml2-devel'
        - 'boost-devel'
        - 'hwloc'
        - 'hwloc-devel'
        - 'sshpass'

    - pip:
        name: pexpect

    - name: download torque source
      get_url:
        url: http://wpfilebase.s3.amazonaws.com/torque/torque-6.1.0.tar.gz
        dest: /root/torque-6.1.0.tar.gz
        checksum: sha256:ae7f0d06d274a1b9d7f9cf378ef518699e347a0d48122658f737f1f31ca4938e

    - name: extract torque
      unarchive:
        src: /root/torque-6.1.0.tar.gz
        dest: /root
        remote_src: True

    - name: run configure
      command: ./configure --enable-cgroups --with-momlogdir
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/config.status

    - name: run make
      command: make
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_success

    - name: test if make worked
      command: touch make_success
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_success

    - name: run make install
      command: make install
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_install_success

    - name: test if make install worked
      command: touch make_install_success
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/make_install_success

    - name: create hwloc config file
      command: touch /etc/ld.so.conf.d/hwloc.conf
      args:
        creates: /etc/ld.so.conf.d/hwloc.conf

    - name: configure hwloc
      lineinfile:
        dest: /etc/ld.so.conf.d/hwloc.conf
        line: '/usr/local/lib'

    - name: run ldconfig
      command: ldconfig

# TODO the hostnamne given by the hostname command, must be the first entry in the /etc/hosts for 127.0.0.1


    - name: initial server db
      expect:
        command: ./torque.setup root
        responses:
          (?i)wish: "y"
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/initial_server_db_success
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/usr/local/sbin"

    - name: create file to show server db initialize worked
      command: touch initial_server_db_success
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/initial_server_db_success

    - name: enable and start pbs_server
      systemd:
        name: pbs_server.service
        state: started
        enabled: True

    - name: (2.2.5) run make packages
      command: make packages
      args:
        chdir: /root/torque-6.1.0
        creates: /root/torque-6.1.0/torque-package-devel-linux-x86_64.sh

    - name: configure nodes
      lineinfile:
        dest: /var/spool/torque/server_priv/nodes
        line: 'client1 np=1 client1'
        create: yes
      become: yes
      become_user: root

    - name: enable and start pbs_server
      systemd:
        name: pbs_server.service
        state: restarted
        enabled: True

- hosts: nodes
  tasks:
    - name: configure hosts file
      lineinfile:
        dest: /etc/hosts
        line: '192.168.50.4 master'
        create: yes
      become: yes
      become_user: root
    # review if all these dependencies needed. hwloc, libcgroup-tools needed.
    - name: install dependencies for mom client
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'libcgroup-tools'
        - 'hwloc'
        - 'hwloc-devel'
        - 'libxml2-devel'
        - 'boost-devel'
        - 'openssl-devel'
        - 'gcc'
        - 'gcc-c++'
        - 'libgcc'
        - 'numactl-libs'
        - 'xz-devel'
      become: yes
      become_user: root

    - name: copy MOM file to clients
      copy:
        src: /root/torque-6.1.0/torque-package-mom-linux-x86_64.sh
        dest: /tmp/torque-package-mom-linux-x86_64.sh
        mode: 0755

    - name: copy mom service unit file
      copy:
        src: /root/torque-6.1.0/contrib/systemd/pbs_mom.service
        dest: /usr/lib/systemd/system/pbs_mom.service
        mode: 0644
      become: yes
      become_user: root

    - name: run mom client install
      command: ./torque-package-mom-linux-x86_64.sh --install
      args:
        chdir: /tmp
      become: yes
      become_user: root

    - name: fix security violation in /var/spool/torque
      file:
        path: /var/spool/torque
        recurse: yes
        state: directory
        owner: root
        group: root
        mode: "0755" # must be quoted or DOOM (octal vs dec)
      become: yes
      become_user: root

    - name: fix security violation in /var/spool/torque
      file:
        path: "{{ item }}"
        recurse: no
        state: directory
        owner: root
        group: root
        mode: "1777" # must be quoted or DOOM (octal vs dec)
      become: yes
      become_user: root
      with_items:
        - '/var/spool/torque/spool'
        - '/var/spool/torque/undelivered'

    - name: configure mom
      lineinfile:
        dest: /var/spool/torque/mom_priv/config
        regexp: '^\$pbsserver'
        line: '$pbsserver master'
        create: yes
      become: yes
      become_user: root

    - name: add log file arguement to /usr/lib/systemd/system/pbs_mom.service
      lineinfile:
        dest: /usr/lib/systemd/system/pbs_mom.service
        regexp: '^ExecStart='
        line: 'ExecStart=/usr/local/sbin/pbs_mom -F -d $PBS_HOME $PBS_ARGS -L /var/spool/torque/mom_logs/pbs_mom.log'
      become: yes
      become_user: root

    - name: reload units
      command:  systemctl daemon-reload
      become: yes
      become_user: root

    - name: enable pbs_mom service
      command:  systemctl enable pbs_mom.service
      become: yes
      become_user: root

    - name: restart mom client
      command:  systemctl restart pbs_mom.service
      become: yes
      become_user: root

    - name: status mom client
      command:  systemctl status pbs_mom.service
      become: yes
      become_user: root
      register: mom_status

    - debug: msg="{{mom_status.stdout}}"



#test torque server
#download maui
#uncompress maui
#configure maui
#make maui
#make install maui
#test maui
#dhcpd on master for pxe of clients
#fix master to client known hosts issue
#fix systemd enable trqauthd
#fix pbs_server does not start on first boot
