---
- hosts: localhost
  tasks:
    - name: download torque source
      get_url:
        url: http://wpfilebase.s3.amazonaws.com/torque/torque-6.1.0.tar.gz
        dest: /root/torque-6.1.0.tar.gz

    - name: install packages for building torque
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'libxml2-devel'
        - 'boost-devel'




    # download torque
    # extract
    # install packages related to rpmbuild
    # build torque rpm
    # scp to file server
